services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5433"
    networks:
      - my-app
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - my-app
    restart: unless-stopped
  restapiapp:
    build: .
    container_name: restApiApp
    ports:
      - "9080:9080"
    depends_on:
      - postgres
      - pgadmin
    networks:
      - my-app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jobapp
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    restart: unless-stopped

networks:
  my-app:
    driver: bridge

volumes:
  postgres:
  pgadmin:
